feat: kratos hydra integration
ory/kratos-selfservice-ui-node pull request #198
Opened 2022-09-13 03:40 UTC by grantzvolsky

This branch is based on the `fix-new-sdk` branch which was ahead of master.

## Related Issue or Design Document

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation within the code base (if appropriate).

## Further comments

2022-09-27 13:23 UTC, grantzvolsky commented on views/login.hbs
> +      <p>To authenticate {{#if hydra_login_request.client.client_name}}{{hydra_login_request.client.client_name}}{{else}}{{hydra_login_request.client.client_id}}{{/if}}</p>
Consider linking to client_uri if set.

2022-09-27 13:24 UTC, grantzvolsky commented on views/registration.hbs
> +      <p>To authenticate {{#if hydra_login_request.client.client_name}}{{hydra_login_request.client.client_name}}{{else}}{{hydra_login_request.client.client_id}}{{/if}}</p>
Consider linking to client_uri if set.

2022-10-04 15:54 UTC, aeneasr requested changes
Just a nit-pick, otherwise LGTM :)

2022-10-04 15:54 UTC, aeneasr commented on src/pkg/ui.ts
> +    switch (node.attributes && node.attributes['type']) {
```suggestion
    switch (node.attributes && node.attributes.type) {
```

2022-10-05 09:08 UTC, merged

2022-10-05 12:43 UTC, jpollard-cs commented
🥳