Routing
ory/kratos-selfservice-ui-node pull request #246
Opened 2023-02-15 10:56 UTC by DavyJohnes

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2023-03-29 12:47 UTC, Benehiko requested changes
I think it makes sense to be able to set a base path. 

I have reviewed the code and there are some unnecessary changes which can be reverted. I will also need take a closer look at the implementation to verify if everything works correctly. Some of these changes could affect the Account Experience which is built on top of this project.

2023-03-29 12:47 UTC, Benehiko commented on src/routes/static.ts
>      res.contentType("text/javascript")
Why move it from Ory Elements?

https://github.com/ory/elements/blob/main/src/markup/express.ts

2023-03-29 12:47 UTC, Benehiko commented on src/index.ts
> +app.use(baseUrl, router)
okay makes sense, I would need to check this out more thoroughly since this application is re-used to create the Ory Network Account Experience.

2023-03-29 12:47 UTC, Benehiko commented on .nvmrc
remove?

2023-03-30 11:44 UTC, Benehiko commented
I checked this out and it seems to change this to use a router. 

I have opened a new PR in Ory Elements which we will merge before this one so we don't need to write the same code for static routes.

2023-03-30 12:39 UTC, Benehiko approved these changes
I think this will be fine now :)

I have updated the Ory Elements package and cleaned up the PR a bit. From my side it should be good to go. @jonas-jonas maybe just take a look if something seems off, I have tested this in Ory Network and everything is working as expected.

2023-03-30 12:49 UTC, jonas-jonas approved these changes
Looks very reasonable. Nice work!

2023-03-30 13:03 UTC, merged